### ISSUE TITLE
Add CSV dump.

### ISSUE THREAD

**Issue by seank** [malcom2073/emstune#27]
In addition to dumping the JSON and BIN stream file, can you export a CSV file too. This would help guys who need to dump data into spread sheets for advance analytics. EMSLogView is great, but for some things spreadsheets work better.

Thanks,
Sean

**Comment by malcom2073** [comment]
Negative, the amount of CPU overhead that would require does not scale very well, not to mention that would *very* quickly take up very large amounts of space. Text is expensive all around.

As an alternative, how about having an option in EMSLogView to export to csv?

**Comment by seank** [comment]
"As an alternative, how about having an option in EMSLogView to export to csv?"

That would be equally awesome :)
